"""
Transcripta
Copyright (c) 2025 Seif Eldeen Fathi
Licensed under a commercial one-time license.
"""

APP_NAME = "Transcripta Lite"

# ---------- Localization (simple key -> translated string) ----------
"""
Localization System Overview

The app uses a simple dictionary-based localization system.
All user interface texts are stored in LANG_STRINGS, organized by language code
(e.g., "en", "ar"). Each language shares the same keys for consistency.

The function get_str(key) returns the translated string according to the
current language, and falls back to English if the key is missing.

"""

LANG_STRINGS = {
    'English': {
        'app_title': APP_NAME,
        "model_desc_tiny": "Tiny — fastest, smallest model. Lowest accuracy but very fast; good for short clips and limited CPU.",
        "model_desc_base": "Base — balanced model. Moderate speed and accuracy, good starting point for many languages.",
        "model_desc_small": "Small — higher accuracy than base, slower. Better for noisy audio or varied accents.",
        "appearance_set": "Appearance set to",
        "transcription_running": "A transcription is already running",
        'Audio_Language': 'Audio Language:',
        "Whisper_model": "The Whisper model",
        "model_not_found": "is not found on this device. It will be downloaded automatically on first use. You can monitor the download in your Terminal.",
        "set_torch_threads": "Set torch threads to ",
        "transcription_finished": "Transcription finished in ",
        "loading_model": "Loading Whisper model",
        'ui_lang_switched': "UI Languege Switched to English",
        "selected_file": "Selected file",
        "using_all": "Using all ",
        "cpu_threads": " CPU threads.",
        "using": "Using ",
        "saved_as": "Saved as",
        "no_text_to_save": "There is no text to save.",
        'text_copied': 'Text copied to clipboard',
        "editor_cleared": "Editor cleared",
        "record": "🎙️ Record",
        "stop_record": "⏹️ Stop",
        "recording_started": "Recording started",
        "recording_stopped": "Recording stopped",
        "recording_saved": "Recording saved",
        "choose_record_format": "Choose recording format",
        "recommendation_text": "🤖 Recommendation: FLAC gives WAV quality with smaller size — good default for transcription.",
        "format_desc_wav": "WAV — highest quality, large file size. Best for maximum transcription fidelity.",
        "format_desc_mp3": "MP3 — compressed, small size, faster upload/processing. Slight quality loss may affect accuracy.",
        "format_desc_wav_mp3": "WAV → MP3 — record in WAV then convert to MP3. Better than direct MP3, smaller than WAV.",
        "format_desc_flac": "FLAC — lossless compression (WAV-quality) with smaller file size. Good balance for transcription.",
        'browse': 'Browse file',
        'play': '▶️Play',
        'select_model': 'Select model:',
        'use_full_cpu': 'When no GPU: use full CPU',
        'progress': 'Transcription progress:',
        'eta': 'ETA:',
        'start': 'Start Transcription',
        'stop': '⏹️ Stop',
        'appearance': 'Appearance:',
        'ui_language': 'UI Language:',
        'copy': 'Copy (Ctrl+C)',
        'save': 'Save',
        'clear': '✖️ Clear',
        'Edit':'✍️ Edit',
        'notifications': 'Notifications',
        'no_file': 'No file selected',
        'no_gpu_popup_title': 'No GPU Detected',
        'no_gpu_popup_msg': 'No GPU detected. The app will run on CPU only. This may be slower.',
        'threads_label': 'CPU Threads',
        'saving_missing_docx': 'python-docx not installed. Saved as .txt instead.',
        'stopping_playback': "Stopping playback...",
        'could_not_play': "Could not play file automatically. Install ffplay or VLC.",
        'playing_file': "Playing file (or opening external player)...",
        'record_failed': "Recording failed or no audio captured.",
        'record_cancelled': "Recording cancelled by user.",
        'conversion_failed': "Conversion failed; transcription aborted.",
        'user_requested_stop': "User requested stop. Current transcribe may still finish (cannot force-stop).",
        'no_transcription_to_stop': "No transcription to stop",
    },
    
    'Arabic': {
        'app_title': APP_NAME,
        
        "model_desc_tiny": "Tiny — \n نموذج وأصغر أسرع \n . الضعيفة الأجهزة أو القصيرة للمقاطع مناسب جدًا سريع لكن أقل دقته",
        "model_desc_base": "Base — \n متوازن نموذج \n. اللغات لمعظم جيدة بداية نقطة، متوسطة ودقة وسرعة  ",
        "model_desc_small": "Small — \n Base من أعلي دقه \n المختلفة اللهجات أو الضوضاء ذات للصوتيات ملائم أبطأ لكن ",
        'Audio_Language': 'الصوت لغة :',
        "transcription_running": "توجد عملة تفريغ بالفعل",
        "Whisper_model": "Whisper موديل",
        "model_not_found": "غير موجود علي هذا الجهاز. سيتم تنزيله تلقائيا من خلال ال terminal",
        "appearance_set": "الي المظهر ضبط تم",
        "set_torch_threads": "خيوط Torch عدد تعيين إلى ",
        "transcription_finished": "خلال التفريخ انهاء تم ",
        "loading_model": "نموذج Whisper تحميل",
        "selected_file": "الملف اختيار تم",
        "using_all": "كل استخدام يتم ",
        "cpu_threads": "المعالج أنوية من ",
        "using": "استخدام يتم ",
        "saved_as": "باسم الحفظ تم",
        "no_text_to_save": "لا يوجد نص لحفظه.",
        "editor_cleared": "المحرر مسح تم",
        'text_copied': 'الحافظة الي النص نسخ تم',
        "record": "🎙️ تسجيل",
        "stop_record": "⏹️ التسجيل ايقاف",
        "Edit" : "✍️ تعديل / تحرير",
        "recording_started": "التسجيل بدء تم",
        "recording_stopped": "التسجيل ايقاف تم",
        "recording_saved": "التسجيل حفظ تم\n",
        "choose_record_format": "التسجيل صيغة أختر",
        "recommendation_text": "🤖 التفريغ ل ممتاز خيار — أصغر بحجم WAV جودة تمنحك FLAC :صيغة التوصية",
        'ui_lang_switched': "العربية الي الواجهة لغه تغيير تم",  
        "format_desc_wav": "، التفريغ في دقة أفضل على للحصول مناسب ،كبير بحجم لكن صوت جودة أعلى — WAV",
        "format_desc_mp3": "، قليلاً تقل قد الدقة لكن، المعالجة في وسريع الحجم وصغير مضغوط — MP3",
        "format_desc_wav_mp3": "، WAV من أصغر وحجم المباشر MP3 من أعلى جودة، MP3 إلى يحوله ثم WAV بصيغة يسجل — MP3 ← WAV",
        "format_desc_flac": "، الحجم وبين الجودة بين ممتاز توازن، أصغر بحجم لكن WAV جودة نفس تقريبًا، الجودة فقدان بدون ضغط — FLAC",
        'browse': 'ملف استعراض',
        'play': '▶️ تشغيل',
        'select_model': 'موديل أختر :',
        'use_full_cpu': 'المعالج كل أستخدم : GPU وجود عدم عند',
        'progress': 'التفريغ تقدم :',
        'eta': 'المتبقي الزمن :',
        'start': 'التفريغ أبدا',
        'stop': '⏹️ إيقاف',
        'appearance': 'الوضع:',
        'ui_language': 'الواجهة لغه :',
        'copy': 'نسخ (Ctrl+C)',
        'save': 'حفظ',
        'clear': '✖️ مسح',
        'notifications': 'الإشعارات',
        'no_file': 'ملف اختيار يتم لم',
        'no_gpu_popup_title': 'لم يتم العثور على GPU',
        'no_gpu_popup_msg': 'لا يوجد GPU. التطبيق سيعمل على CPU فقط. قد يكون أبطأ.',
        'threads_label': 'المعالج أنويه (Threads)',
        'saving_missing_docx': 'python-docx غير مثبت. تم الحفظ كملف نصي.',
        'stopping_playback': "التشغيل ايقاف...",
        'could_not_play': "تلقائيًا الملف تشغيل تعذر. VLC أو ffplay تثبيت يرجى",
        'playing_file': "... خارجي مشغل فتح أو (الملف تشغيل يتم)",
        'record_failed': ".صوت التقاط يتم لم أو التسجيل فشل",
        'record_cancelled': ".المستخدم بواسطة التسجيل إلغاء تم",
        'conversion_failed': ".التفريغ عملية إلغاء تم؛ التحويل فشل",
        'user_requested_stop': ".بالقوة إيقافها يمكن لا (تكتمل حتى التفريغ عملية تستمر قد) الإيقاف طلب المستخدم",
        'no_transcription_to_stop': ".للإيقاف التفريغ عملية توجد لا",
    },
    
    'French': {
        'app_title': APP_NAME,
        "model_desc_tiny": "Tiny — le modèle le plus rapide et le plus petit. Moins précis mais très rapide; idéal pour les courts extraits et les CPU limitées.",
        "model_desc_base": "Base — modèle équilibré. Vitesse et précision modérées; bon point de départ pour de nombreuses langues.",
        "model_desc_small": "Small — plus précis que Base mais plus lent. Mieux adapté aux enregistrements bruyants ou aux accents variés.",
        "Whisper_model": "Le modèle Whisper",
        "transcription_running": "Une transcription est déjà en cours",
        'Audio_Language': 'Langue Audio:',
        "model_not_found": "n'est pas trouvé sur cet appareil. Il sera téléchargé automatiquement lors de la première utilisation. Vous pouvez suivre le téléchargement dans votre terminal.",
        "appearance_set": "Apparence définie sur",
        "set_torch_threads": "Définir les threads Torch sur ",
        "transcription_finished": "Transcription terminée en ",
        "loading_model": "Chargement du modèle Whisper",
        'text_copied': 'Texte copié dans le presse-papiers',
        "selected_file": "Fichier sélectionné",
        "using_all": "Utilisation de tous les ",
        "cpu_threads": " threads du processeur.",
        "using": "Utilisation de ",
        "saved_as": "Enregistré sous",
        "no_text_to_save": "Il n'y a pas de texte à enregistrer.",
        "editor_cleared": "Éditeur effacé",
        "record": "🎙️ Enregistrer",
        "stop_record": "⏹️ Arrêter",
        "recording_started": "Enregistrement démarré",
        "recording_stopped": "Enregistrement arrêté",
        "recording_saved": "Enregistrement sauvegardé",
        'Edit': '✍️ Éditer' , 
        "choose_record_format": "Choisir le format d'enregistrement",
        "recommendation_text": "🤖 Recommandation : FLAC offre la qualité du WAV avec une taille réduite — bon choix par défaut pour la transcription.",
        'ui_lang_switched': "Langue de l’interface changée en français",
        "format_desc_wav": "WAV — meilleure qualité sonore, taille de fichier importante. Idéal pour une transcription très précise.",
        "format_desc_mp3": "MP3 — compressé, taille réduite, plus rapide à traiter, mais légère perte de qualité.",
        "format_desc_wav_mp3": "WAV → MP3 — enregistrement en WAV puis conversion en MP3. Meilleure qualité que le MP3 direct, taille inférieure au WAV.",
        "format_desc_flac": "FLAC — compression sans perte, qualité équivalente au WAV avec une taille plus réduite. Bon équilibre pour la transcription.",
        'browse': 'Parcourir le fichier',
        'play': '▶️ Lecture',
        'select_model': 'Choisir le modèle :',
        'use_full_cpu': "Sans GPU : utiliser tout le CPU",
        'progress': 'Progression :',
        'eta': 'ETA :',
        'start': 'Lancer la transcription',
        'stop': '⏹️ Arrêter',
        'appearance': 'Apparence :',
        'ui_language': 'Langue UI :',
        'copy': 'Copier (Ctrl+C)',
        'save': 'Enregistrer',
        'clear': '✖️ Effacer',
        'notifications': 'Notifications',
        'no_file': 'Aucun fichier sélectionné',
        'no_gpu_popup_title': 'GPU non détecté',
        'no_gpu_popup_msg': "Aucun GPU détecté. L'application utilisera le CPU. Cela peut être plus lent.",
        'threads_label': 'Threads CPU',
        'saving_missing_docx': "python-docx non installé. Sauvegarde en .txt.",
        'stopping_playback': "Arrêt de la lecture...",
        'could_not_play': "Impossible de lire le fichier automatiquement. Installez ffplay ou VLC.",
        'playing_file': "Lecture du fichier (ou ouverture du lecteur externe)...",
        'record_failed': "Échec de l'enregistrement ou aucun son capturé.",
        'record_cancelled': "Enregistrement annulé par l'utilisateur.",
        'conversion_failed': "Échec de la conversion ; transcription annulée.",
        'user_requested_stop': "Arrêt demandé par l'utilisateur. La transcription actuelle peut encore se terminer (arrêt forcé impossible).",
        'no_transcription_to_stop': "Aucune transcription à arrêter.",
    },
    
    'German': {
        'app_title': APP_NAME,
        "model_desc_tiny": "Tiny — das schnellste und kleinste Modell. Niedrigste Genauigkeit, aber sehr schnell; gut für kurze Clips und schwache CPUs.",
        "model_desc_base": "Base — ausgewogenes Modell. Mittlere Geschwindigkeit und Genauigkeit; guter Ausgangspunkt für viele Sprachen.",
        "model_desc_small": "Small — höhere Genauigkeit als Base, aber langsamer. Besser für laute Audiodateien oder verschiedene Akzente.",
        "Whisper_model": "Das Whisper Modell",
        "transcription_running": "Eine Transkription läuft bereits",
        'Audio_Language': 'Audio-Sprache:',
        "model_not_found": "wurde auf diesem Gerät nicht gefunden. Es wird beim ersten Gebrauch automatisch heruntergeladen. Sie können den Download in Ihrem Terminal überwachen.",
        "appearance_set": "Darstellung eingestellt auf",
        "set_torch_threads": "Torch-Threads festlegen auf ",
        "transcription_finished": "Transkription beendet in ",
        "loading_model": "Whisper-Modell wird geladen",
        'ui_lang_switched': "Oberflächensprache auf Deutsch geändert",
        "selected_file": "Ausgewählte Datei",
        "using_all": "Verwende alle ",
        "cpu_threads": " CPU-Threads.",
        "using": "Verwende ",
        "saved_as": "Gespeichert als",
        "no_text_to_save": "Es gibt keinen Text zum Speichern.",
        "editor_cleared": "Editor geleert",
        'text_copied': 'Text in die Zwischenablage kopiert',
        "record": "🎙️ Aufnahme",
        "stop_record": "⏹️ Stopp",
        "recording_started": "Aufnahme gestartet",
        "recording_stopped": "Aufnahme gestoppt",
        "recording_saved": "Aufnahme gespeichert",
        "choose_record_format": "Aufnahmeformat wählen",
        "recommendation_text": "🤖 Empfehlung: FLAC bietet WAV-Qualität bei kleinerer Dateigröße — gute Standardwahl für Transkription.",
        "format_desc_wav": "WAV — höchste Tonqualität, große Dateigröße. Am besten für maximale Transkriptionsgenauigkeit.",
        "format_desc_mp3": "MP3 — komprimiert, kleine Datei, schnellere Verarbeitung, leichte Qualitätsverluste möglich.",
        "format_desc_wav_mp3": "WAV → MP3 — Aufnahme in WAV, dann Umwandlung in MP3. Bessere Qualität als direktes MP3, kleiner als WAV.",
        "format_desc_flac": "FLAC — verlustfreie Kompression mit WAV-Qualität, aber kleinerer Dateigröße. Guter Kompromiss für Transkription.",
        'browse': 'Datei öffnen',
        'Edit': '✍️ Bearbeiten',
        'play': '▶️ Abspielen',
        'select_model': 'Modell wählen:',
        'use_full_cpu': 'Wenn kein GPU: gesamten CPU nutzen',
        'progress': 'Transkriptionsfortschritt:',
        'eta': 'Verbleibende Zeit:',
        'start': 'Transkription starten',
        'stop': '⏹️ Stopp',
        'appearance': 'Darstellung:',
        'ui_language': 'UI-Sprache:',
        'copy': 'Kopieren (Ctrl+C)',
        'save': 'Speichern',
        'clear': '✖️ Löschen',
        'notifications': 'Benachrichtigungen',
        'no_file': 'Keine Datei ausgewählt',
        'no_gpu_popup_title': 'Keine GPU gefunden',
        'no_gpu_popup_msg': 'Keine GPU erkannt. Anwendung verwendet CPU. Kann langsamer sein.',
        'threads_label': 'CPU-Threads',
        'saving_missing_docx': 'python-docx nicht installiert. Als .txt gespeichert.',
        'stopping_playback': "Wiedergabe wird gestoppt...",
        'could_not_play': "Datei konnte nicht automatisch abgespielt werden. Installieren Sie ffplay oder VLC.",
        'playing_file': "Datei wird abgespielt (oder externer Player wird geöffnet)...",
        'record_failed': "Aufnahme fehlgeschlagen oder kein Audio erfasst.",
        'record_cancelled': "Aufnahme vom Benutzer abgebrochen.",
        'conversion_failed': "Konvertierung fehlgeschlagen; Transkription abgebrochen.",
        'user_requested_stop': "Benutzer hat Stopp angefordert. Die aktuelle Transkription kann noch abgeschlossen werden (kein erzwungener Stopp möglich).",
        'no_transcription_to_stop': "Keine Transkription zu stoppen.",
    },
    # Additional languages (basic translations)
    'Spanish': {
        'app_title': APP_NAME,
        "model_desc_tiny": "Tiny — el modelo más rápido y pequeño. Menor precisión pero muy rápido; ideal para clips cortos y CPU limitadas.",
        "model_desc_base": "Base — modelo equilibrado. Velocidad y precisión moderadas; buen punto de partida para muchos idiomas.",
        "model_desc_small": "Small — mayor precisión que Base, pero más lento. Mejor para audio con ruido o diferentes acentos.",
        "Whisper_model": "El modelo Whisper",
        "transcription_running": "Ya hay una transcripción en ejecución",
        'Audio_Language': 'Idioma de Audio:',
        "model_not_found": "no se encuentra en este dispositivo. Se descargará automáticamente en el primer uso. Puedes supervisar la descarga en tu Terminal.",
        "appearance_set": "Apariencia configurada en",
        "set_torch_threads": "Establecer los hilos de Torch en ",
        "transcription_finished": "Transcripción finalizada en ",
        "loading_model": "Cargando modelo Whisper",
        "selected_file": "Archivo seleccionado ",
        "using_all": "Usando todos los",
        "cpu_threads": " hilos de CPU.",
        "using": "Usando ",
        'text_copied': 'Texto copiado al portapapeles',
        "no_text_to_save": "No hay texto para guardar.",
        "saved_as": "Guardado como",
        "editor_cleared": "Editor borrado",
        "record": "🎙️ Grabar",
        "stop_record": "⏹️ Detener",
        "recording_started": "Grabación iniciada",
        "recording_stopped": "Grabación detenida",
        "recording_saved": "Grabación guardada",
        "choose_record_format": "Elegir formato de grabación",
        'Edit': '✍️ Editar',
        'ui_lang_switched': "Idioma de la interfaz cambiado a español",
        "recommendation_text": "🤖 Recomendación: FLAC ofrece calidad WAV con menor tamaño — buena opción predeterminada para transcripción.",
        "format_desc_wav": "WAV — máxima calidad de audio, tamaño de archivo grande. Ideal para una transcripción precisa.",
        "format_desc_mp3": "MP3 — comprimido, tamaño pequeño, procesamiento más rápido, ligera pérdida de calidad.",
        "format_desc_wav_mp3": "WAV → MP3 — graba en WAV y luego convierte a MP3. Mejor calidad que MP3 directo y tamaño menor que WAV.",
        "format_desc_flac": "FLAC — compresión sin pérdida (misma calidad que WAV) pero con tamaño menor. Buen equilibrio para transcripción.",
        'browse': 'Buscar archivo', 
        'play': '▶️ Reproducir', 
        'select_model': 'Seleccionar modelo:', 'use_full_cpu': 'Sin GPU: usar CPU completo',
        'progress': 'Progreso:', 
        'eta': 'ETA:', 
        'start': 'Iniciar transcripción', 
        'stop': '⏹️ Detener', 
        'appearance': 'Apariencia:', 
        'ui_language': 'Idioma UI:',
        'copy': 'Copiar (Ctrl+C)', 
        'save': 'Guardar', 
        'clear': '✖️ Limpiar', 
        'notifications': 'Notificaciones', 
        'no_file': 'No hay archivo seleccionado',
        'no_gpu_popup_title': 'GPU no detectada', 
        'no_gpu_popup_msg': 'No se detectó GPU. Usando CPU.', 
        'threads_label': 'Hilos CPU', 
        'saving_missing_docx': 'python-docx no instalado.',
        'stopping_playback': "Deteniendo la reproducción...",
        'could_not_play': "No se pudo reproducir el archivo automáticamente. Instale ffplay o VLC.",
        'playing_file': "Reproduciendo archivo (o abriendo reproductor externo)...",
        'record_failed': "Error en la grabación o no se capturó audio.",
        'record_cancelled': "Grabación cancelada por el usuario.",
        'conversion_failed': "Error en la conversión; transcripción cancelada.",
        'user_requested_stop': "El usuario solicitó detener. La transcripción actual puede continuar (no se puede forzar la detención).",
        'no_transcription_to_stop': "No hay transcripción para detener.",
    },
    
    'Italian': {
        'app_title': APP_NAME,"model_desc_tiny": "Tiny — il modello più veloce e più piccolo. Precisione inferiore ma molto rapido; buono per clip brevi e CPU limitate.",
        "model_desc_base": "Base — modello bilanciato. Velocità e precisione moderate, un buon punto di partenza per molte lingue.",
        "model_desc_small": "Small — maggiore precisione rispetto a Base, ma più lento. Meglio per audio rumorosi o accenti vari.",
        "Whisper_model": "Il modello Whisper",
        "transcription_running": "È già in esecuzione una trascrizione",
        'Audio_Language': 'Lingua Audio:',
        "model_not_found": "non è presente su questo dispositivo. Verrà scaricato automaticamente al primo utilizzo. Puoi monitorare il download dal Terminale.",
        "appearance_set": "Aspetto impostato su",
        "set_torch_threads": "Imposta i thread di Torch su ",
        "transcription_finished": "Trascrizione completata in ",
        "loading_model": "Caricamento del modello Whisper",
        "selected_file": "File selezionato",
        "using_all": "Utilizzando tutti i ",
        "cpu_threads": " thread della CPU.",
        "using": "Utilizzando ",
        'text_copied': 'Testo copiato negli appunti',
        "no_text_to_save": "Non c'è testo da salvare.",
        "saved_as": "Salvato come",
        "editor_cleared": "Editor cancellato",
        "record": "🎙️ Registra",
        "stop_record": "⏹️ Ferma",
        "recording_started": "Registrazione avviata",
        "recording_stopped": "Registrazione interrotta",
        "recording_saved": "Registrazione salvata",
        "choose_record_format": "Scegli formato di registrazione",
        'Edit': '✍️ Modifica',
        'ui_lang_switched': "Lingua dell’interfaccia cambiata in italiano",
        "recommendation_text": "🤖 Consiglio: FLAC offre qualità WAV con dimensioni ridotte — ottima scelta predefinita per la trascrizione.",
        "format_desc_wav": "WAV — massima qualità audio, file di grandi dimensioni. Ideale per trascrizioni molto accurate.",
        "format_desc_mp3": "MP3 — compresso, piccolo, più veloce da elaborare ma con leggera perdita di qualità.",
        "format_desc_wav_mp3": "WAV → MP3 — registra in WAV e poi converte in MP3. Migliore qualità rispetto a MP3 diretto, dimensione inferiore a WAV.",
        "format_desc_flac": "FLAC — compressione senza perdita, stessa qualità del WAV ma file più piccolo. Buon compromesso per trascrizione.",
        'browse': 'Sfoglia file', 
        'play': '▶️ Riproduci', 
        'select_model': 'Seleziona modello:', 
        'use_full_cpu': 'Senza GPU: usa tutto CPU',
        'progress': 'Progresso:', 
        'eta': 'ETA:', 
        'start': 'Avvia trascrizione', 
        'stop': '⏹️ Interrompi', 
        'appearance': 'Aspetto:', 
        'ui_language': 'Lingua UI:',
        'copy': 'Copia (Ctrl+C)', 
        'save': 'Salva', 
        'clear': '✖️ Pulisci', 
        'notifications': 'Notifiche', 
        'no_file': 'Nessun file selezionato',
        'no_gpu_popup_title': 'GPU non rilevata', 
        'no_gpu_popup_msg': 'Nessuna GPU trovata. Uso CPU.', 
        'threads_label': 'Thread CPU', 
        'saving_missing_docx': 'python-docx non installato.',
        'stopping_playback': "Interruzione della riproduzione...",
        'could_not_play': "Impossibile riprodurre automaticamente il file. Installa ffplay o VLC.",
        'playing_file': "Riproduzione del file (o apertura di un lettore esterno)...",
        'record_failed': "Registrazione non riuscita o nessun audio catturato.",
        'record_cancelled': "Registrazione annullata dall'utente.",
        'conversion_failed': "Conversione non riuscita; trascrizione annullata.",
        'user_requested_stop': "Interruzione richiesta dall'utente. La trascrizione corrente potrebbe continuare (non è possibile interromperla forzatamente).",
        'no_transcription_to_stop': "Nessuna trascrizione da interrompere.",
    },
    
    'Turkish': {
        'app_title': APP_NAME,"model_desc_tiny": "Tiny — en hızlı ve en küçük model. Düşük doğruluk ancak çok hızlı; kısa klipler ve sınırlı CPU için uygundur.",
        "model_desc_base": "Base — dengeli model. Orta hız ve doğruluk; birçok dil için iyi bir başlangıç noktasıdır.",
        "model_desc_small": "Small — Base’den daha yüksek doğrulukta ancak daha yavaş. Gürültülü sesler veya farklı aksanlar için daha uygundur.",
        "Whisper_model": "Whisper modeli",
        "transcription_running": "Zaten bir transkripsiyon çalışıyor",
        'Audio_Language': 'Ses Dili:',
        "model_not_found": "bu cihazda bulunamadı. İlk kullanımda otomatik olarak indirilecektir. İndirmeyi Terminal üzerinden takip edebilirsiniz.",
        "appearance_set": "Görünüm ayarlandı:",
        "set_torch_threads": "Torch iş parçacıklarını ayarla: ",
        "transcription_finished": "Dönüştürme şu sürede tamamlandı ",
        "loading_model": "Whisper modeli yükleniyor",
        "selected_file": "Seçilen dosya",
        "using_all": "Tüm" ,
        "cpu_threads": " CPU iş parçacıkları kullanılıyor.",
        "using": "Kullanılıyor ",
        'text_copied': 'Metin panoya kopyalandı',
        "no_text_to_save": "Kaydedilecek metin yok.",
        "saved_as": "Olarak kaydedildi",
        "editor_cleared": "Düzenleyici temizlendi",
        "record": "🎙️ Kaydet",
        "stop_record": "⏹️ Durdur",
        "recording_started": "Kayıt başladı",
        "recording_stopped": "Kayıt durduruldu",
        "recording_saved": "Kayıt kaydedildi",
        "choose_record_format": "Kayıt formatını seç",
        'Edit': '✍️ Düzenle',
        'ui_lang_switched': "Arayüz dili Türkçeye değiştirildi",
        "recommendation_text": "🤖 Öneri: FLAC, WAV kalitesini daha küçük boyutta sunar — transkripsiyon için iyi bir varsayılan seçenektir.",
        "format_desc_wav": "WAV — en yüksek ses kalitesi, büyük dosya boyutu. En iyi transkripsiyon doğruluğu için idealdir.",
        "format_desc_mp3": "MP3 — sıkıştırılmış, küçük boyutlu, daha hızlı işlem, ancak hafif kalite kaybı olabilir.",
        "format_desc_wav_mp3": "WAV → MP3 — WAV olarak kaydedip sonra MP3'e dönüştürür. Doğrudan MP3'ten daha kaliteli, WAV'dan daha küçük.",
        "format_desc_flac": "FLAC — kayıpsız sıkıştırma, WAV kalitesiyle ama daha küçük boyut. Transkripsiyon için iyi bir denge.",
        'browse': 'Dosya Seç', 
        'play': '▶️ Oynat', 
        'select_model': 'Model seç:', 
        'use_full_cpu': 'GPU yoksa tüm CPU kullan',
        'progress': 'İlerleme:', 
        'eta': 'Kalan süre:', 
        'start': 'Transkripti Başlat', 
        'stop': '⏹️ Durdur', 
        'appearance': 'Görünüm:', 
        'ui_language': 'Arayüz Dili:',
        'copy': 'Kopyala (Ctrl+C)', 
        'save': 'Kaydet', 
        'clear': '✖️Temizle', 
        'notifications': 'Bildirimler', 
        'no_file': 'Dosya seçilmedi',
        'no_gpu_popup_title': 'GPU bulunamadı', 
        'no_gpu_popup_msg': 'GPU tespit edilmedi. CPU kullanılacak.', 
        'threads_label': 'CPU İş Parçacığı', 
        'saving_missing_docx': 'python-docx yüklü değil.',
        'stopping_playback': "Oynatma durduruluyor...",
        'could_not_play': "Dosya otomatik olarak oynatılamadı. ffplay veya VLC yükleyin.",
        'playing_file': "Dosya oynatılıyor (veya harici oynatıcı açılıyor)...",
        'record_failed': "Kayıt başarısız oldu veya ses yakalanmadı.",
        'record_cancelled': "Kayıt kullanıcı tarafından iptal edildi.",
        'conversion_failed': "Dönüştürme başarısız; yazıya dökme iptal edildi.",
        'user_requested_stop': "Kullanıcı durdurma istedi. Mevcut yazıya dökme devam edebilir (zorla durdurulamaz).",
        'no_transcription_to_stop': "Durdurulacak bir yazıya dökme yok.",
    },
    
    'Chinese': {
        'app_title': APP_NAME,"model_desc_tiny": "Tiny — 最快、最小的模型。精度最低，但速度非常快；适合短音频和有限的 CPU。",
        "model_desc_base": "Base — 平衡模型。速度和精度适中，是多语言任务的良好起点。",
        "model_desc_small": "Small — 比 Base 精度更高但更慢。适合噪声较多或口音多样的音频。",
        "Whisper_model": "Whisper模型",
        "transcription_running": "转录已经在运行中",
        'Audio_Language': '音频语言:',
        "model_not_found": "在此设备上未找到。首次使用时将自动下载。您可以在终端监控下载情况。",
        "appearance_set": "外观设置为",
        "set_torch_threads": "将 Torch 线程设置为 ",
        "transcription_finished": "转录完成，用时 ",
        "loading_model": "正在加载 Whisper 模型",
        "selected_file": "已选择文件 ",
        "using_all": " 正在使用全部",
        "cpu_threads": " CPU 线程。",
        "using": "正在使用 ",
        "no_text_to_save": "没有可保存的文本。",
        "saved_as": "保存为",
        "editor_cleared": "编辑器已清空",
        'text_copied': '文本已复制到剪贴板',
        "record": "🎙️ 录音",
        "stop_record": "⏹️ 停止录音",
        "recording_started": "录音已开始",
        "recording_stopped": "录音已停止",
        "recording_saved": "录音已保存",
        "choose_record_format": "选择录音格式",
        'Edit': '✍️ 编辑',
        'ui_lang_switched': "界面语言已切换为中文",
        "format_desc_wav": "WAV — 最高音质，但文件较大。适合追求最高转录精度的情况。",
        "format_desc_mp3": "MP3 — 压缩格式，文件小，处理更快，但音质略有损失。",
        "format_desc_wav_mp3": "WAV → MP3 — 先录制为WAV再转换为MP3，质量高于直接MP3，体积小于WAV。",
        "format_desc_flac": "FLAC — 无损压缩，音质与WAV相同但体积更小，是质量与体积的良好平衡。",
        "recommendation_text": "🤖 推荐：FLAC 提供与 WAV 相同的音质，但文件更小 — 转录的理想默认选项。",
        'browse': '选择文件', 
        'play': '▶️ 播放', 
        'select_model': '选择模型：', 
        'use_full_cpu': '无GPU时：使用全部CPU',
        'progress': '进度：', 
        'eta': '预计：', 
        'start': '开始转录', 
        'stop': '⏹️ 停止', 
        'appearance': '外观：', 
        'ui_language': '界面语言：',
        'copy': '复制 (Ctrl+C)', 
        'save': '保存', 
        'clear': '✖️ 清除', 
        'notifications': '通知', 
        'no_file': '未选择文件',
        'no_gpu_popup_title': '未检测到GPU', 
        'no_gpu_popup_msg': '未检测到GPU。应用将使用CPU。可能更慢。', 
        'threads_label': 'CPU 线程', 'saving_missing_docx': '未安装 python-docx。',
        'stopping_playback': "正在停止播放...",
        'could_not_play': "无法自动播放文件。请安装 ffplay 或 VLC。",
        'playing_file': "正在播放文件（或打开外部播放器）...",
        'record_failed': "录音失败或未捕获到声音。",
        'record_cancelled': "录音已被用户取消。",
        'conversion_failed': "转换失败；转录已中止。",
        'user_requested_stop': "用户请求停止。当前转录可能仍会完成（无法强制停止）。",
        'no_transcription_to_stop': "没有可停止的转录。",
    },
    
    'Russian': {
        'app_title': APP_NAME, "model_desc_tiny": "Tiny — самая быстрая и компактная модель. Низкая точность, но высокая скорость; подходит для коротких аудио и слабых CPU.",
        "model_desc_base": "Base — сбалансированная модель. Средняя скорость и точность, хорошее начало для многих языков.",
        "model_desc_small": "Small — более высокая точность, чем у Base, но медленнее. Лучше подходит для шумных аудио или разных акцентов.",
        "Whisper_model": "Модель Whisper",
        "transcription_running": "Транскрипция уже запущена",
        'Audio_Language': 'Язык аудио:',
        "model_not_found": "не найдена на этом устройстве. Будет автоматически загружена при первом использовании. Вы можете отслеживать загрузку в терминале.",
        "appearance_set": "Внешний вид установлен на",
        "set_torch_threads": "Установить потоки Torch на ",
        "transcription_finished": "Транскрипция завершена за ",
        "loading_model": "Загрузка модели Whisper",
        'text_copied': 'Текст скопирован в буфер обмена',
        "selected_file": "Выбранный файл ",
        "using_all": "Используются все",
        "cpu_threads": " потоки процессора.",
        "using": "Используются ",
        "no_text_to_save": "Нет текста для сохранения.",
        "saved_as": "Сохранено как",
        "editor_cleared": "Редактор очищен",
        "record": "🎙️ Запись",
        "stop_record": "⏹️ Остановить",
        "recording_started": "Запись начата",
        "recording_stopped": "Запись остановлена",
        "recording_saved": "Запись сохранена",
        "choose_record_format": "Выберите формат записи",
        'Edit': '✍️ Редактировать',
        'ui_lang_switched': "Язык интерфейса изменён на русский",
        "recommendation_text": "🤖 Рекомендация: FLAC обеспечивает качество WAV при меньшем размере файла — хороший выбор по умолчанию для транскрипции.",
        "format_desc_wav": "WAV — наивысшее качество звука, большой размер файла. Лучше всего для точной транскрипции.",
        "format_desc_mp3": "MP3 — сжатый формат, маленький размер, быстрая обработка, но лёгкая потеря качества.",
        "format_desc_wav_mp3": "WAV → MP3 — запись в WAV, затем конвертация в MP3. Лучше, чем прямой MP3, меньше по размеру, чем WAV.",
        "format_desc_flac": "FLAC — сжатие без потерь, то же качество, что и WAV, но меньший размер. Хороший баланс для транскрипции.",
        'browse': 'Выбрать файл', 
        'play': '▶️ Воспроизведение', 
        'select_model': 'Выберите модель:', 
        'use_full_cpu': 'Если нет GPU: использовать CPU полностью',
        'progress': 'Прогресс:', 
        'eta': 'Осталось:', 
        'start': 'Начать транскрипцию', 
        'stop': '⏹️Остановить', 
        'appearance': 'Вид:', 
        'ui_language': 'Язык интерфейса:',
        'copy': 'Копировать (Ctrl+C)', 
        'save': 'Сохранить', 
        'clear': '✖️Очистить', 
        'notifications': 'Уведомления', 
        'no_file': 'Файл не выбран',
        'no_gpu_popup_title': 'GPU не обнаружено', 
        'no_gpu_popup_msg': 'GPU не найден. Используется CPU.', 
        'threads_label': 'Потоки CPU', 
        'saving_missing_docx': 'python-docx не установлен.',
        'stopping_playback': "Остановка воспроизведения...",
        'could_not_play': "Не удалось автоматически воспроизвести файл. Установите ffplay или VLC.",
        'playing_file': "Воспроизведение файла (или открытие внешнего плеера)...",
        'record_failed': "Не удалось записать или не был захвачен звук.",
        'record_cancelled': "Запись отменена пользователем.",
        'conversion_failed': "Ошибка конвертации; транскрипция отменена.",
        'user_requested_stop': "Пользователь запросил остановку. Текущая транскрипция может быть завершена (нельзя принудительно остановить).",
        'no_transcription_to_stop': "Нет транскрипции для остановки.",
        'no_file': "Файл не выбран",
    },
    
    'Japanese': {
        'app_title': APP_NAME, "model_desc_tiny": "Tiny — 最も高速で最小のモデル。精度は低いが非常に速く、短いクリップやCPU性能が限られた環境に最適。",
        "model_desc_base": "Base — バランスの取れたモデル。速度と精度のバランスが良く、多くの言語に適しています。",
        "model_desc_small": "Small — Baseより高精度だが、速度は遅い。ノイズの多い音声や様々なアクセントに適しています。",
        "Whisper_model": "Whisper モデル",
        "transcription_running": "文字起こしはすでに実行中です",
        'Audio_Language': 'オーディオ言語:',
        "model_not_found": "このデバイスには見つかりません。初回使用時に自動的にダウンロードされます。ダウンロードはターミナルで確認できます。",
        "appearance_set": "外観が次に設定されました",
        "set_torch_threads": "Torch のスレッドを次に設定 ",
        "transcription_finished": "文字起こしが完了しました（所要時間：） ",
        "selected_file": "選択されたファイル",
        "loading_model": "Whisper モデルを読み込み中",
        "using_all": "すべての ",
        "cpu_threads": " CPUスレッドを使用中。",
        "using": "使用中 ",
        'text_copied': 'テキストがクリップボードにコピーされました',
        "no_text_to_save": "保存するテキストがありません。",
        "saved_as": "として保存しました",
        "editor_cleared_ja": "エディタがクリアされました",
        "record": "🎙️ 録音",
        "stop_record": "⏹️ 停止",
        "recording_started": "録音を開始しました",
        "recording_stopped": "録音を停止しました",
        "recording_saved": "録音を保存しました",
        "choose_record_format": "録音形式を選択",
        'Edit': '✍️ 編集',
        "recommendation_text": "🤖 推奨: FLAC は WAV と同じ音質で、ファイルサイズが小さい — 文字起こしに最適なデフォルトです。",
        "format_desc_wav": "WAV — 最高音質ですがファイルサイズが大きい。正確な文字起こしに最適です。",
        "format_desc_mp3": "MP3 — 圧縮形式でサイズが小さく処理が速いが、音質がやや低下する可能性があります。",
        "format_desc_wav_mp3": "WAV → MP3 — WAVで録音後MP3に変換。直接MP3より高音質で、WAVより小さいサイズ。",
        "format_desc_flac": "FLAC — 可逆圧縮で音質はWAVと同じだが、ファイルサイズは小さい。文字起こしに最適なバランス。",
        'ui_lang_switched': "UI 言語が日本語に変更されました",
        'browse': 'ファイルを開く', 
        'play': '▶️ 再生', 
        'select_model': 'モデル選択:', 
        'use_full_cpu': 'GPUがない場合は全CPUを使用',
        'progress': '進行状況:', 
        'eta': '残り時間:', 
        'start': '文字起こし開始', 
        'stop': '⏹️ 停止', 
        'appearance': '表示:', 
        'ui_language': 'UI言語:',
        'copy': 'コピー (Ctrl+C)', 
        'save': '保存', 
        'clear': '✖️ クリア', 
        'notifications': '通知', 
        'no_file': 'ファイル未選択',
        'no_gpu_popup_title': 'GPUが見つかりません', 
        'no_gpu_popup_msg': 'GPUが検出されません。CPUで実行します。遅くなる場合があります。', 
        'threads_label': 'CPUスレッド', 
        'saving_missing_docx': 'python-docxがインストールされていません.',
        'stopping_playback': "再生を停止しています...",
        'could_not_play': "ファイルを自動的に再生できません。ffplay または VLC をインストールしてください。",
        'playing_file': "ファイルを再生中（または外部プレーヤーを開いています）...",
        'record_failed': "録音に失敗したか、音声が取得されませんでした。",
        'record_cancelled': "録音がユーザーによってキャンセルされました。",
        'conversion_failed': "変換に失敗しました。文字起こしを中止します。",
        'user_requested_stop': "ユーザーが停止を要求しました。現在の文字起こしは終了するまで続く可能性があります（強制停止はできません）。",
        'no_transcription_to_stop': "停止する文字起こしがありません。",
    }
}

WHISPER_LANGS = {
    "Auto Detect": None,
    "Afrikaans": "af",
    "Albanian": "sq",
    "Amharic": "am",
    "Arabic": "ar",
    "Armenian": "hy",
    "Assamese": "as",
    "Azerbaijani": "az",
    "Bashkir": "ba",
    "Basque": "eu",
    "Belarusian": "be",
    "Bengali": "bn",
    "Bosnian": "bs",
    "Breton": "br",
    "Bulgarian": "bg",
    "Burmese": "my",
    "Catalan": "ca",
    "Chinese": "zh",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Dutch": "nl",
    "English": "en",
    "Estonian": "et",
    "Faroese": "fo",
    "Finnish": "fi",
    "French": "fr",
    "Galician": "gl",
    "Georgian": "ka",
    "German": "de",
    "Greek": "el",
    "Gujarati": "gu",
    "Haitian Creole": "ht",
    "Hausa": "ha",
    "Hawaiian": "haw",
    "Hebrew": "he",
    "Hindi": "hi",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Indonesian": "id",
    "Italian": "it",
    "Japanese": "ja",
    "Javanese": "jv",
    "Kannada": "kn",
    "Kazakh": "kk",
    "Khmer": "km",
    "Korean": "ko",
    "Lao": "lo",
    "Latin": "la",
    "Latvian": "lv",
    "Lingala": "ln",
    "Lithuanian": "lt",
    "Luxembourgish": "lb",
    "Macedonian": "mk",
    "Malagasy": "mg",
    "Malay": "ms",
    "Malayalam": "ml",
    "Maltese": "mt",
    "Maori": "mi",
    "Marathi": "mr",
    "Mongolian": "mn",
    "Nepali": "ne",
    "Norwegian": "no",
    "Occitan": "oc",
    "Pashto": "ps",
    "Persian": "fa",
    "Polish": "pl",
    "Portuguese": "pt",
    "Punjabi": "pa",
    "Romanian": "ro",
    "Russian": "ru",
    "Sanskrit": "sa",
    "Serbian": "sr",
    "Shona": "sn",
    "Sindhi": "sd",
    "Sinhala": "si",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Somali": "so",
    "Spanish": "es",
    "Sundanese": "su",
    "Swahili": "sw",
    "Swedish": "sv",
    "Tagalog": "tl",
    "Tajik": "tg",
    "Tamil": "ta",
    "Tatar": "tt",
    "Telugu": "te",
    "Thai": "th",
    "Tibetan": "bo",
    "Turkish": "tr",
    "Turkmen": "tk",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Uzbek": "uz",
    "Vietnamese": "vi",
    "Welsh": "cy",
    "Yiddish": "yi",
    "Yoruba": "yo",
}
